# Generated by Django 2.2.16 on 2023-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230313_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
